"""empty message

Revision ID: 59914b183082
Revises: 22593bbefc63
Create Date: 2020-09-20 05:38:19.050782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59914b183082'
down_revision = '22593bbefc63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reduction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('up', sa.Integer(), nullable=True),
    sa.Column('down', sa.Integer(), nullable=True),
    sa.Column('light', sa.Integer(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('green', sa.Integer(), nullable=True),
    sa.Column('wash', sa.Integer(), nullable=True),
    sa.Column('dry', sa.Integer(), nullable=True),
    sa.Column('fridge', sa.Integer(), nullable=True),
    sa.Column('furnace', sa.Integer(), nullable=True),
    sa.Column('windows', sa.Integer(), nullable=True),
    sa.Column('main', sa.Integer(), nullable=True),
    sa.Column('gcar', sa.Integer(), nullable=True),
    sa.Column('ecar', sa.Integer(), nullable=True),
    sa.Column('bus', sa.Integer(), nullable=True),
    sa.Column('train', sa.Integer(), nullable=True),
    sa.Column('plane', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user_info', 'df3')
    op.drop_column('user_info', 'enSource')
    op.drop_column('user_info', 'df2')
    op.drop_column('user_info', 'enAmt')
    op.drop_column('user_info', 'lf3')
    op.drop_column('user_info', 'bf3')
    op.drop_column('user_info', 'bf2')
    op.drop_column('user_info', 'distance')
    op.drop_column('user_info', 'transport')
    op.drop_column('user_info', 'bf1')
    op.drop_column('user_info', 'lf2')
    op.drop_column('user_info', 'df1')
    op.drop_column('user_info', 'lf1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('lf1', sa.VARCHAR(length=100), nullable=True))
    op.add_column('user_info', sa.Column('df1', sa.VARCHAR(length=100), nullable=True))
    op.add_column('user_info', sa.Column('lf2', sa.VARCHAR(length=100), nullable=True))
    op.add_column('user_info', sa.Column('bf1', sa.VARCHAR(length=100), nullable=True))
    op.add_column('user_info', sa.Column('transport', sa.VARCHAR(length=100), nullable=True))
    op.add_column('user_info', sa.Column('distance', sa.INTEGER(), nullable=True))
    op.add_column('user_info', sa.Column('bf2', sa.VARCHAR(length=100), nullable=True))
    op.add_column('user_info', sa.Column('bf3', sa.VARCHAR(length=100), nullable=True))
    op.add_column('user_info', sa.Column('lf3', sa.VARCHAR(length=100), nullable=True))
    op.add_column('user_info', sa.Column('enAmt', sa.INTEGER(), nullable=True))
    op.add_column('user_info', sa.Column('df2', sa.VARCHAR(length=100), nullable=True))
    op.add_column('user_info', sa.Column('enSource', sa.VARCHAR(length=100), nullable=True))
    op.add_column('user_info', sa.Column('df3', sa.VARCHAR(length=100), nullable=True))
    op.drop_table('reduction')
    # ### end Alembic commands ###
