"""info table

Revision ID: f2c385768eb3
Revises: 4b03132af670
Create Date: 2020-09-20 00:26:32.228909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c385768eb3'
down_revision = '4b03132af670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('bf1', sa.String(length=100), nullable=True),
    sa.Column('bf2', sa.String(length=100), nullable=True),
    sa.Column('bf3', sa.String(length=100), nullable=True),
    sa.Column('lf1', sa.String(length=100), nullable=True),
    sa.Column('lf2', sa.String(length=100), nullable=True),
    sa.Column('lf3', sa.String(length=100), nullable=True),
    sa.Column('df1', sa.String(length=100), nullable=True),
    sa.Column('df2', sa.String(length=100), nullable=True),
    sa.Column('df3', sa.String(length=100), nullable=True),
    sa.Column('transport', sa.String(length=100), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('enSource', sa.String(length=100), nullable=True),
    sa.Column('enAmt', sa.Integer(), nullable=True),
    sa.Column('totalOut', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    # ### end Alembic commands ###
